server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:usuarios
    username: sa
    password:
    initialization-mode: always
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        show-sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  ##hibernate:
    ##ddl-auto: true

api:
  regex:
    pass: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()?[{}]:;',?/*~$^+=<>]).{8,15}$"
    passmessage: "La clave debe tener al menos una letra mayúscula, una minúscula, un número y un caracter especial"
  security:
    authentication:
      jwt:
        secret: NJuYliUuZWCtRFCGkDHiRW+M6p1EM0BO4EmW9AdxWnVwoAdSHcdIxs97KEej1qcPviZSXzhjynbO2TwIeEPzng===
        token-validity-in-seconds: 86400
